version: "3"

services:
  site:
    build:
      context: ./
      args:
        - UID=${UID}
    image: afropython-site-image
    container_name: afropython-site
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/site:rw,cached
